apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.5.0
        volumeMounts:
          - mountPath: "/loki-store"
            name: loki-store
          - mountPath: "/etc/loki"
            name: loki-config
      volumes:
        - name: loki-store
          persistentVolumeClaim:
            claimName: loki-store
        - name: loki-config
          configMap:
            name: loki-config