apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-store
spec:
  resources:
    requests:
      storage: 10G
  volumeMode: Filesystem
  storageClassName: thin-csi
  accessModes:
    - ReadWriteOnce
